### ISSUE TITLE
jenkins-automation & jenkins-as-code-starter-project seed job

### ISSUE THREAD

**Issue by joshmyers** [cfpb/jenkins-automation#131]
Appreciate this maybe more an issue with the https://github.com/cfpb/jenkins-as-code-starter-project repo

I'd like to check out this project but am having issues with the seed job. https://github.com/cfpb/jenkins-as-code-starter-project/blob/master/README.md#creating-the-seed-job states that you will need a multiscm for both the automation and jenkins as code repo. Assuming this is not directing me to checkout both repos to the same top level directory, I have:

```
ls -ll /var/jenkins_home/jobs/jenkins-dsl-seed/workspace/
total 8
drwxr-xr-x 8 jenkins jenkins 4096 Jan 30 14:52 jenkins-automation
drwxr-xr-x 7 jenkins jenkins 4096 Jan 30 14:52 jenkins-jobs
```

but when I run this job, looking for `jenkins-jobs/jobs/*.groovy` I'm getting `unable to resolve class BaseJobBuilder` errors, which is to be expected. I have tried setting the `additionalClasspath: jenkins-automation/src/main/groovy` to no avail. My seed jobs is:

```
job('seed') {
    multiscm {
        git {
            remote {
                name('origin')
                github('cfpb/jenkins-automation', 'https')
            }
            branch('*/master')
                configure { node ->
                    node / 'extensions' << 'hudson.plugins.git.extensions.impl.RelativeTargetDirectory' {
                        relativeTargetDir('jenkins-automation')
                    }
                }
        }
        git {
            remote {
                name('origin')
                github('joshmyers/jenkins-jobs', 'https')
            }
            branch('*/master')
                configure { node ->
                    node / 'extensions' << 'hudson.plugins.git.extensions.impl.RelativeTargetDirectory' {
                        relativeTargetDir('jenkins-jobs')
                    }
                }
        }
    }
    steps {
        gradle 'clean test'
        dsl {
            external 'jobs/**/*Jobs.groovy'
            additionalClasspath 'jenkins-automation/src/main/groovy'
        }
    }
}
```

It works if I just clone `jenkins-automate` and run the example jobs from the seed, but I'd rather not fork and hack on this repo and use the jenkins-as-code-starter-project.

Any ideas?

**Comment by acrewdson** [comment]
@joshmyers did you figure this out?

**Comment by wingy3181** [comment]
@acrewdson I had the same problem with my own jobs and the additionalClasspath setting did work for me

**Comment by acrewdson** [comment]
@wingy3181 Thanks for the feedback. It sounds like you were able to get things working. I'm thinking we might need to improve the README in this project, or in the example project, to make this point clearer?
