### ISSUE TITLE
How do you use BaseJob directly in a script?

### ISSUE THREAD

**Issue by marcesher** [cfpb/jenkins-automation#35]
The examples.md show usage of BaseJob, but the example has this:

`build(factory)`

However, `factory` does not exist in a script.

All other examples of BaseBuilder are inside of other builders, where factory does exist

Please correct this example

**Comment by imuchnik** [comment]
Done.

**Comment by marcesher** [comment]
Done how? What kind of issue closing is this?

**Comment by imuchnik** [comment]
@marcesher  I corrected the example, just like you asked. What is the protocol for fixing markdown and closing an issue?

**Comment by marcesher** [comment]
@imuchnik ah, I didn't see you had fixed it. I think a link to the fix is sufficient... referencing the issue number in the commit will ensure it gets auto-added here, i.e. "closes #35"

Thanks!
