### ISSUE TITLE
BuildFlowJob: default to requiring a workspace

### ISSUE THREAD

**Issue by marcesher** [cfpb/jenkins-automation#50]
create all build flow jobs with a workspace. Near as I can tell, there's no downside, all upside

**Comment by marcesher** [comment]
accomplished with:

```
buildFlowJob('example') {
    buildNeedsWorkspace()
}
```

Though this does require `v1.42` of the job-dsl-plugin to be installed

**Comment by marcesher** [comment]
hmmm...

when I updated my jenkins to the latest job-dsl, configure blocks started failing. Let's hold off on this.

**Comment by marcesher** [comment]
ok, figured it out. The failing configure block is the one in the example job with buildNeedsWorkspace. It fails because that method now exists as of 1.42. I'll update the example job to show how to do it in earlier and the most recent version of job-dsl

**Comment by imuchnik** [comment]
plugin dependency bumped to 1.42
